import type { FoodId } from './nutrition/foods';
import type { Ingredient, Recipe, RecipeId } from './types';

/** [qty shown, item shown] or, to count it in nutrition, [..., food, grams]. */
type IngredientRow =
  | readonly [qty: string, item: string]
  | readonly [qty: string, item: string, food: FoodId, grams: number];

type RecipeInput = Omit<Recipe, 'id' | 'ingredients'> & {
  ingredients: readonly IngredientRow[];
};

function define(recipes: Record<RecipeId, RecipeInput>): Record<RecipeId, Recipe> {
  const out = {} as Record<RecipeId, Recipe>;
  for (const id of Object.keys(recipes) as RecipeId[]) {
    const { ingredients, ...rest } = recipes[id];
    out[id] = {
      id,
      ...rest,
      ingredients: ingredients.map((row): Ingredient =>
        row.length === 4
          ? { qty: row[0], item: row[1], amount: { food: row[2], grams: row[3] } }
          : { qty: row[0], item: row[1] },
      ),
    };
  }
  return out;
}

/*
 * House rules for every recipe (see CLAUDE.md): halal; sweet paprika only, nothing hot;
 * onion and garlic only grated into long-cooked sauces, never raw; no vinegar; tomato kept low.
 * Chicken is skinless and oil is measured: the plan targets ~1,700 kcal/day for fat loss.
 */
export const RECIPES = define({
  loubia: {
    name: 'Loubia with beef',
    short: 'Loubia',
    local: 'Loubia bel lham',
    kind: 'stew',
    week: 1,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 35 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min, stir halfway (stove: small pot, splash of water, 6 min).',
    cutter: [
      { head: 'slice-thick', what: '3 carrots' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      [
        '400 g',
        'dried white beans, soaked overnight and drained (or 3 × 400 g cans, drained)',
        'white-beans',
        400,
      ],
      ['600 g', 'lean beef chunks (épaule), 3 cm cubes', 'beef-chunks', 600],
      ['1', 'onion, finely grated on the cutter. It melts into the sauce', 'onion', 150],
      ['2 cloves', 'garlic, grated (optional, fully cooked)'],
      ['3', 'carrots, thick slices on the cutter', 'carrot', 300],
      ['2 tbsp', 'tomato paste', 'tomato-paste', 30],
      ['1 tsp', 'sweet paprika (paprika douce)'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'black pepper'],
      ['1', 'bay leaf'],
      ['1½ tsp', 'salt'],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['1.2 L', 'water (1.8 L if using the stove)'],
      ['handful', 'parsley, chopped'],
    ],
    steps: [
      'Sauté mode: heat the oil and brown the beef with the grated onion and garlic for 8 minutes.',
      'Stir in the tomato paste, paprika, cumin and pepper. Cook 1 minute.',
      'Add the drained beans, carrots, bay leaf, salt and water. Close the lid.',
      'Pressure 35 minutes, then let the pressure drop on its own for 10 minutes.',
      "Taste for salt. If it's thin, simmer on sauté with the lid off for 5 minutes. Finish with parsley.",
    ],
    alternative:
      'Slow cook: boil the soaked beans hard in plain water for 10 minutes first (slow cookers never get hot enough to make dried beans safe), then 7–8 hours on low. Or a covered pot on the stove for about 1½ hours until the beans are soft.',
  },
  bolognese: {
    name: 'Beef & lentil bolognese',
    short: 'Bolognese',
    local: 'Not Algerian, but a freezer classic',
    kind: 'pot',
    week: 1,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot + pasta pot, stove',
    time: '25 min hands-on · 30 min simmer',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Splash of water, lid ajar, microwave 3 min, stir halfway.',
    cutter: [
      { head: 'slice-thin', what: '200 g mushrooms' },
      { head: 'grate-coarse', what: '2 zucchini' },
      { head: 'grate-fine', what: '3 carrots' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['600 g', 'lean beef mince (viande hachée)', 'beef-mince', 600],
      [
        '200 g',
        'red lentils, rinsed. They melt into the sauce and add protein and fibre',
        'red-lentils',
        200,
      ],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['3', 'carrots, finely grated on the cutter', 'carrot', 300],
      ['2', 'zucchini, coarsely grated on the cutter', 'zucchini', 500],
      ['200 g', 'mushrooms, thin slices on the cutter', 'mushrooms', 200],
      ['500 g', 'tomato passata (1 bottle)', 'passata', 500],
      ['1 tbsp', 'tomato paste', 'tomato-paste', 15],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['1 tsp', 'dried thyme or oregano'],
      ['1', 'bay leaf'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['¼ tsp', 'baking soda (bicarbonate). Takes the acid edge off the tomato'],
      ['500 ml', 'water'],
      ['to serve', '360 g whole-wheat pasta (60 g per portion)', 'pasta-ww', 360],
    ],
    steps: [
      'Big pot, high heat: oil, then the mince. Break it up and brown for 6–8 minutes.',
      'Add the onion, carrots, zucchini and mushrooms. Cook 8 minutes, stirring, until the vegetables are soft and the liquid has cooked off.',
      'Stir in the tomato paste, passata, lentils, water, herbs, bay leaf, salt, pepper and baking soda (it foams for a moment).',
      'Simmer half-covered for 30 minutes, stirring now and then, until the lentils have melted into the sauce.',
      "Meanwhile, boil the pasta 2 minutes less than the packet says and drain. Toss it with a ladle of sauce so it doesn't stick.",
      'Portion pasta and sauce into containers.',
    ],
  },
  'paprika-tray': {
    name: 'Paprika chicken, potatoes & carrots',
    short: 'Paprika chicken',
    kind: 'tray',
    week: 1,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '15 min hands-on · 45 min oven',
    keeps: "Fridge 4 days · Don't freeze (the potatoes go grainy)",
    reheat: 'Microwave 2 min, or air fryer 180°C for 6–8 min to make it crisp again.',
    cutter: [{ head: 'slice-thick', what: '600 g potatoes, 3 carrots, 1 zucchini' }],
    ingredients: [
      ['1.2 kg', 'chicken legs, skin removed (ask the butcher), bone-in', 'chicken-leg', 1200],
      ['600 g', 'potatoes, thick slices on the cutter', 'potato', 600],
      ['3', 'carrots, thick slices on the cutter', 'carrot', 300],
      ['1', 'zucchini, thick slices on the cutter', 'zucchini', 250],
      ['1', 'sweet pepper (not hot), in strips', 'pepper', 150],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['2 tsp', 'sweet paprika'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'turmeric'],
      ['1 tsp', 'dried thyme'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
    ],
    steps: [
      'Oven to 210°C (gas 7). Line 2 trays with baking paper.',
      'In a big bowl, mix the oil, spices and salt. Toss the chicken and vegetables in it until everything is coated.',
      'Spread in one layer over both trays so nothing is crowded (crowded vegetables steam instead of roasting). Chicken on top of the vegetables so its juices baste them.',
      "Roast 40–45 minutes and swap the trays halfway. It's done when the chicken juices run clear and the potato slices are golden at the edges.",
    ],
  },
  'tajine-chickpea': {
    name: 'Chicken & chickpea tajine',
    short: 'Chicken tajine',
    local: 'Tajine djej bel hummus',
    kind: 'stew',
    week: 2,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '15 min hands-on · 15 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min with the lid ajar. Sprinkle 1 tbsp water over the couscous first.',
    cutter: [
      { head: 'slice-thick', what: '4 carrots, 2 zucchini' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['1.2 kg', 'chicken legs, skin removed, bone-in (6 small pieces)', 'chicken-leg', 1200],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['2 cloves', 'garlic, grated (optional)'],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['1 tsp', 'ginger powder'],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1½ tsp', 'salt'],
      ['400 g', 'cooked chickpeas (1 can, or 150 g dried and soaked)', 'chickpeas', 400],
      ['4', 'carrots, thick slices on the cutter', 'carrot', 400],
      ['2', 'zucchini, thick slices on the cutter', 'zucchini', 500],
      ['500 ml', 'water (800 ml if using the stove)'],
      ['handful', 'coriander and parsley'],
      [
        'to serve',
        '240 g whole-wheat couscous (40 g per portion, see Couscous)',
        'couscous-ww',
        240,
      ],
    ],
    steps: [
      'Sauté mode: oil, chicken, onion, garlic, spices and salt. Stir for 8 minutes.',
      'Add the chickpeas, carrots and water. Pressure 15 minutes, then quick release.',
      'Add the zucchini. Sauté mode with the lid off for 5–6 minutes, until the zucchini is just tender and the sauce has reduced.',
      'Stir in the herbs. Put couscous in each container and add the tajine on top.',
    ],
    alternative:
      'Slow cook: 5–6 hours on low (zucchini for the last hour). On the stove: covered pot for 45 minutes, adding the zucchini for the last 15.',
  },
  'lentil-soup': {
    name: 'Red lentil & carrot soup',
    short: 'Lentil soup',
    local: 'Chorba adès',
    kind: 'pot',
    week: 2,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot + hand blender',
    time: '10 min hands-on · 25 min simmer',
    keeps: 'Fridge 4 days · Freezer 3 months',
    reheat:
      'Splash of water, microwave 3 min. Eat it with the boiled egg and bread from the plate.',
    cutter: [
      { head: 'slice-thin', what: '3 carrots, 1 potato' },
      { head: 'grate-coarse', what: '1 onion' },
    ],
    ingredients: [
      ['400 g', 'red lentils, rinsed', 'red-lentils', 400],
      ['1', "onion, coarsely grated on the cutter (blended in, you won't taste it)", 'onion', 150],
      ['3', 'carrots, thin slices on the cutter', 'carrot', 300],
      ['1', 'medium potato, thin slices on the cutter', 'potato', 200],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'turmeric'],
      ['1 tsp', 'sweet paprika'],
      ['1', 'chicken stock cube'],
      ['2.2 L', 'water'],
      ['1 tsp', 'salt (taste first, the cube is salty)'],
    ],
    steps: [
      'Big pot: oil and onion for 5 minutes, until soft but not brown.',
      'Add the carrots, potato and spices and stir for 1 minute. Thin slices cook fast.',
      'Add the lentils, water and stock cube. Bring to a boil, then simmer partly covered for 20–25 minutes, stirring now and then.',
      'Blend smooth with the hand blender. Taste and add salt.',
    ],
  },
  'kefta-tray': {
    name: 'Baked kefta with potatoes & peppers',
    short: 'Kefta tray',
    local: 'Kefta au four',
    kind: 'tray',
    week: 2,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '25 min hands-on · 40 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Microwave 2 min or air fryer 180°C for 6 min. Yogurt sauce cold on the side.',
    cutter: [
      { head: 'slice-thick', what: '600 g potatoes, 1 zucchini' },
      { head: 'grate-coarse', what: '½ cucumber (for the sauce)' },
      { head: 'grate-fine', what: '1 small onion' },
    ],
    ingredients: [
      ['600 g', 'lean minced beef (viande hachée)', 'beef-mince', 600],
      [
        '1 small',
        'onion, finely grated on the cutter and squeezed dry (optional, it cooks into the meat)',
        'onion',
        80,
      ],
      ['handful', 'parsley, finely chopped'],
      ['1 tsp', 'cumin'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['1 tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['1', 'egg', 'egg', 55],
      ['3 tbsp', 'oats or breadcrumbs', 'oats', 25],
      ['600 g', 'potatoes, thick slices on the cutter', 'potato', 600],
      ['2', 'sweet peppers, in strips', 'pepper', 300],
      ['1', 'zucchini, thick slices on the cutter', 'zucchini', 250],
      ['1 tbsp', 'olive oil + ½ tsp salt + ½ tsp paprika for the vegetables', 'olive-oil', 14],
      ['2 pots', 'plain yogurt for the sauce', 'yogurt', 220],
      ['½', 'cucumber, coarsely grated on the cutter and squeezed, for the sauce', 'cucumber', 150],
      ['pinch', 'salt and ½ tsp dried mint for the sauce. No garlic'],
    ],
    steps: [
      'Oven to 210°C. Toss the potatoes and vegetables with oil, salt and paprika on 2 trays. Roast 15 minutes.',
      'Meanwhile, mix all the kefta ingredients with your hands for 1 minute. With wet hands, shape about 16 small sausages.',
      'Add the kefta to the trays. Roast 20–25 minutes more and turn them once.',
      'Sauce: stir the yogurt, cucumber, salt and mint together. It keeps 3 days in the fridge.',
    ],
  },
  jelbana: {
    name: 'Peas with beef & carrots',
    short: 'Jelbana',
    local: 'Jelbana',
    kind: 'stew',
    week: 3,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '15 min hands-on · 30 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min, stir halfway.',
    cutter: [
      { head: 'slice-thick', what: '3 carrots' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['700 g', 'lean beef chunks (or skinless chicken legs)', 'beef-chunks', 700],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1½ tsp', 'salt'],
      ['3', 'carrots, thick slices on the cutter', 'carrot', 300],
      ['800 g', 'frozen peas', 'peas', 800],
      ['700 ml', 'water'],
      ['1 bunch', 'coriander, chopped'],
    ],
    steps: [
      'Sauté mode: oil, beef, onion, spices and salt. Stir for 8 minutes.',
      'Add the carrots and water. Pressure 25 minutes, then quick release.',
      'Add the frozen peas. Pressure 3 minutes (or simmer 10 minutes on sauté).',
      'Stir in the coriander.',
    ],
    alternative:
      'Slow cook: beef and carrots 7 hours on low, peas for the last 30 minutes. On the stove: 1 hour covered for the beef, then the peas for the last 15 minutes.',
  },
  'chorba-beida': {
    name: 'White chicken & chickpea soup',
    short: 'Chorba beida',
    local: 'Chorba beida',
    kind: 'pot',
    week: 3,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot, stove',
    time: '15 min hands-on · 45 min simmer',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Add a good splash of water (the vermicelli soaks up liquid). Microwave 3 min.',
    cutter: [
      { head: 'grate-coarse', what: '1 zucchini' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['1.4 kg', 'chicken legs, skin removed, bone-in', 'chicken-leg', 1400],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      [
        '1',
        'zucchini, coarsely grated on the cutter. It disappears into the broth and adds vegetables',
        'zucchini',
        250,
      ],
      ['1 tbsp', 'olive oil (or butter)', 'olive-oil', 14],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1', 'chicken stock cube'],
      ['1 tsp', 'salt'],
      ['400 g', 'cooked chickpeas', 'chickpeas', 400],
      ['2.5 L', 'water'],
      ['100 g', "vermicelli (cheveux d'ange)", 'pasta', 100],
      ['1 bunch', 'parsley, chopped'],
    ],
    steps: [
      "Big pot: oil, chicken, onion, cinnamon and pepper for 6 minutes. Keep it pale, don't brown it.",
      'Add the water, chickpeas, zucchini, stock cube and salt. Simmer covered for 35 minutes.',
      'Lift out the chicken, shred it and throw away the bones.',
      'Add the vermicelli and cook 8 minutes. Put the chicken back and add the parsley.',
      'The traditional finish is egg yolk and lemon. Skip it, because lemon can bring on heartburn.',
    ],
  },
  'yogurt-tray': {
    name: 'Yogurt-marinated chicken with rice',
    short: 'Yogurt chicken',
    local: 'Mild, shawarma-style',
    kind: 'tray',
    week: 3,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '220°C (gas 7–8)',
    time: '15 min hands-on · 30 min marinate · 30 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Sprinkle 1 tbsp water over the rice, microwave 2 min. Yogurt-mint sauce on the side.',
    cutter: [{ head: 'slice-thick', what: '2 zucchini' }],
    ingredients: [
      ['800 g', 'boneless skinless chicken thighs', 'chicken-thigh', 800],
      ['200 g', 'plain yogurt', 'yogurt', 200],
      ['1 tbsp', 'olive oil for the marinade', 'olive-oil', 14],
      ['2 tsp', 'sweet paprika'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'turmeric'],
      ['½ tsp', 'cinnamon'],
      ['1 tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['3', 'sweet peppers, in strips', 'pepper', 450],
      ['2', 'zucchini, thick slices on the cutter', 'zucchini', 500],
      ['2 tsp', 'olive oil + pinch of salt for the vegetables', 'olive-oil', 7],
      ['to serve', '200 g rice (50 g per portion, see Rice)', 'rice', 200],
    ],
    steps: [
      'Mix the yogurt, oil, spices and salt. Coat the chicken and rest 30 minutes (or overnight on Saturday).',
      'Oven to 220°C. Vegetables with oil and salt on one tray, chicken spread out on the other.',
      'Roast 25–30 minutes, until the chicken has dark edges.',
      'Cook the rice while it roasts. Slice the chicken. Portion rice, chicken and vegetables into containers.',
    ],
  },
  zitoune: {
    name: 'Chicken with olives & mushrooms',
    short: 'Tajine zitoune',
    local: 'Tajine zitoune',
    kind: 'stew',
    week: 4,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 15 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min with 1 tbsp water over the rice.',
    cutter: [
      { head: 'slice-thick', what: '3 carrots, 250 g mushrooms' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['1.5 kg', 'chicken legs, skin removed, bone-in', 'chicken-leg', 1500],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'ginger powder'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['½ tsp', 'salt (the olives are salty)'],
      ['3', 'carrots, thick slices on the cutter', 'carrot', 300],
      ['250 g', 'mushrooms, thick slices on the cutter (or 1 can)', 'mushrooms', 250],
      ['200 g', 'pitted green olives', 'olives', 200],
      ['500 ml', 'water'],
      ['handful', 'parsley'],
      ['to serve', '300 g rice (50 g per portion, see Rice)', 'rice', 300],
    ],
    steps: [
      'Olives: boil 5 minutes in plain water and drain. This takes out the extra salt and bitterness.',
      'Sauté mode: oil, chicken, onion, spices and salt for 8 minutes.',
      'Add the carrots, mushrooms and water. Pressure 15 minutes, then quick release.',
      'Add the olives. Sauté mode with the lid off for 8 minutes to thicken. Taste before adding any salt. Parsley on top.',
    ],
    alternative:
      'Slow cook: 5–6 hours on low, olives for the last 30 minutes. On the stove: covered pot for 45 minutes, olives for the last 10.',
  },
  gratin: {
    name: 'Chicken & mushroom pasta bake',
    short: 'Pasta gratin',
    local: 'Gratin de pâtes, lighter',
    kind: 'pot',
    week: 4,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven dish + stove',
    temp: '200°C (gas 6)',
    time: '30 min hands-on · 25 min oven',
    keeps: 'Fridge 4 days · Freezer 2 months',
    reheat: 'Covered, with a splash of milk: microwave 3 min, or oven 180°C for 15 min.',
    cutter: [
      { head: 'slice-thin', what: '200 g mushrooms' },
      { head: 'grate-coarse', what: '1 zucchini (it melts into the sauce)' },
    ],
    ingredients: [
      ['400 g', 'whole-wheat penne', 'pasta-ww', 400],
      ['700 g', 'chicken breast, small cubes', 'chicken-breast', 700],
      ['2 tsp', 'olive oil + ½ tsp sweet paprika + pinch of salt', 'olive-oil', 10],
      ['1', 'zucchini, coarsely grated on the cutter', 'zucchini', 250],
      ['200 g', 'mushrooms, thin slices on the cutter', 'mushrooms', 200],
      ['30 g', 'butter', 'butter', 30],
      ['40 g', 'flour', 'flour-white', 40],
      ['800 ml', 'semi-skimmed milk', 'milk', 800],
      ['1 tsp', 'salt'],
      ['¼ tsp', 'black pepper · pinch of nutmeg'],
      ['120 g', 'grated cheese', 'grated-cheese', 120],
    ],
    steps: [
      'Oven to 200°C. Boil the pasta 2 minutes less than the packet says and drain.',
      'Pan: oil, chicken, paprika and salt for 6 minutes. Add the zucchini and mushrooms for 5 more.',
      "Béchamel: melt the butter in a pot and whisk in the flour for 1 minute. Pour in the milk slowly, whisking all the time, and simmer 5 minutes until it's as thick as yogurt. Add salt, pepper and nutmeg.",
      'Mix the pasta, chicken and half the béchamel in a large oven dish. Pour the rest on top and add the cheese.',
      'Bake 25 minutes until golden. Cool, then cut into 6.',
    ],
  },
  'herb-tray': {
    name: 'Herb drumsticks, sweet potato & green beans',
    short: 'Herb drumsticks',
    kind: 'tray',
    week: 4,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '15 min hands-on · 45 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Microwave 2 min, or air fryer 180°C for 6–8 min.',
    cutter: [{ head: 'slice-thick', what: '600 g sweet potatoes' }],
    ingredients: [
      ['1.4 kg', 'chicken drumsticks, skin removed (about 10)', 'chicken-drumstick', 1400],
      ['600 g', 'sweet potatoes (batata hlowa), thick slices on the cutter', 'sweet-potato', 600],
      ['400 g', 'green beans, trimmed (fresh or frozen)', 'green-beans', 400],
      ['2 tbsp', 'olive oil', 'olive-oil', 27],
      ['1 tsp', 'dried thyme (zaatar)'],
      ['1 tsp', 'sweet paprika'],
      ['1 tbsp', 'honey', 'honey', 15],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
    ],
    steps: [
      'Oven to 210°C. Toss the drumsticks and sweet potato with oil, thyme, paprika, salt and pepper on 2 trays.',
      'Roast 25 minutes.',
      'Add the green beans (tossed in a little oil from the bowl and a pinch of salt) and drizzle the honey over the sweet potatoes.',
      'Roast 20 minutes more. The drumsticks are done when the juices run clear.',
    ],
  },
  oats: {
    name: 'Overnight oats jars',
    short: 'Overnight oats',
    kind: 'breakfast',
    serves: 5,
    yieldUnit: 'jars',
    appliance: 'none',
    where: '5 jars',
    time: '10 min · no cooking',
    keeps: 'Fridge 5 days',
    reheat: 'Eat cold, or warm it for 1 min. Add half a banana in the morning.',
    ingredients: [
      ['250 g', 'rolled oats (50 g per jar)', 'oats', 250],
      ['750 ml', 'semi-skimmed milk, or half milk half lben', 'milk', 750],
      ['2 pots', 'plain yogurt', 'yogurt', 220],
      ['1 tsp', 'cinnamon'],
      ['6', 'dates, chopped (they sweeten it, no honey needed)', 'dates', 48],
      ['small handful', 'almonds or walnuts, chopped', 'nuts', 25],
    ],
    steps: [
      'Put 50 g oats in each jar.',
      'Divide the milk, yogurt, cinnamon, dates and nuts between the jars.',
      'Close and shake. Into the fridge.',
      'Each morning: add half a banana.',
    ],
  },
  muffins: {
    name: 'Egg muffins',
    short: 'Egg muffins',
    kind: 'breakfast',
    serves: 12,
    yieldUnit: 'muffins',
    appliance: 'oven',
    where: '12-cup muffin tin',
    temp: '180°C (gas 4)',
    time: '10 min hands-on · 22 min oven',
    keeps: 'Fridge 3 days · Freezer 2 months',
    reheat:
      '2 muffins: microwave 45 s or air fryer 170°C for 4 min. Add bread and a piece of fruit.',
    cutter: [{ head: 'grate-coarse', what: '1 zucchini (squeeze it dry in a cloth)' }],
    ingredients: [
      ['10', 'eggs', 'egg', 550],
      ['100 ml', 'milk', 'milk', 100],
      ['40 g', 'grated cheese', 'grated-cheese', 40],
      ['1', 'zucchini, coarsely grated on the cutter and squeezed dry', 'zucchini', 250],
      ['1', 'sweet pepper, small dice', 'pepper', 150],
      [
        '100 g',
        'turkey breast slices (blanc de dinde), diced, or leftover chicken',
        'turkey-slices',
        100,
      ],
      ['handful', 'parsley'],
      ['½ tsp', 'salt · pinch of pepper'],
      ['1 tsp', 'oil for the tin', 'olive-oil', 5],
    ],
    steps: [
      'Oven to 180°C. Oil the tin well, including silicone ones.',
      'Whisk the eggs, milk, salt and pepper.',
      'Divide the zucchini, pepper, turkey, cheese and parsley between the cups. Pour the egg over until each is ¾ full.',
      'Bake 20–22 minutes until the centres are set. Cool.',
      '6 go in the fridge (Mon–Wed), 6 go in the freezer (Thu, Fri + spare).',
    ],
  },
  'energy-balls': {
    name: 'Date & oat energy balls',
    short: 'Energy balls',
    kind: 'snack',
    serves: 16,
    yieldUnit: 'balls',
    appliance: 'none',
    where: 'Hand blender chopper',
    time: '15 min · no cooking',
    keeps: 'Fridge 2 weeks',
    reheat: 'One ball = a sweet bite. Good with tea when you would otherwise reach for biscuits.',
    ingredients: [
      ['200 g', 'soft dates (deglet nour), pitted', 'dates', 200],
      ['100 g', 'rolled oats', 'oats', 100],
      ['60 g', 'peanut butter or tahini', 'peanut-butter', 60],
      ['50 g', 'almonds, walnuts or peanuts', 'nuts', 50],
      ['pinch', 'cinnamon'],
      ['1–2 tbsp', 'water if needed'],
    ],
    steps: [
      'Pulse the nuts and oats in the chopper.',
      "Add the dates, peanut butter and cinnamon. Blend until it clumps together, adding a little water if it's dry.",
      'Roll into about 16 balls. Keep in a closed box in the fridge.',
    ],
  },
  couscous: {
    name: 'Couscous, the fast way',
    short: 'Couscous',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'none',
    where: 'Bowl + kettle',
    time: '7 min',
    keeps: 'Fridge 4 days · Freezer (with the stew) 3 months',
    reheat: "Sprinkle with water before microwaving so it doesn't dry out.",
    ingredients: [
      ['240 g', 'whole-wheat couscous (couscous complet), or regular', 'couscous-ww', 240],
      ['1 tsp', 'olive oil', 'olive-oil', 5],
      ['½ tsp', 'salt'],
      ['300 ml', 'boiling water'],
    ],
    steps: [
      'Rub the couscous with the oil and salt in a bowl.',
      'Pour over the boiling water, cover with a plate and wait 7 minutes (5 for regular couscous).',
      'Fluff with a fork. (Steaming it in a couscoussier tastes better, but this is the weekday version.)',
    ],
  },
  rice: {
    name: 'Rice on the stove',
    short: 'Rice',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Pot with lid',
    time: '25 min, mostly waiting',
    keeps: 'Fridge 3 days (cool it fast) · Freezer 2 months',
    reheat: '1 tbsp water on top, microwave covered until steaming.',
    ingredients: [
      ['240–300 g', 'rice (the week tells you how much)'],
      ['2 ×', 'its weight in water'],
      ['½ tsp', 'salt'],
    ],
    steps: [
      'Rinse the rice until the water runs clearer.',
      'Bring the rice, water and salt to a boil. Put the lid on and turn to the lowest heat for 15 minutes.',
      'Take off the heat and leave 10 minutes without lifting the lid.',
      'Cool it fast: spread it on a tray and get it into containers and the fridge within 1 hour.',
    ],
  },
  eggs: {
    name: 'Boiled eggs for the week',
    short: 'Boiled eggs',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Small pot',
    time: '12 min',
    keeps: 'Fridge 7 days, unpeeled',
    reheat: 'Snacks and soup nights use them.',
    ingredients: [['6', 'eggs', 'egg', 330]],
    steps: [
      'Lower the eggs into boiling water with a spoon.',
      'Boil 10 minutes.',
      'Move them to cold water, then into the fridge with the shells on.',
    ],
  },
  kesra: {
    name: 'Whole-wheat kesra',
    short: 'Kesra',
    local: 'Kesra khmira, the healthier version',
    kind: 'basic',
    serves: 18,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Non-stick pan or clay tajine',
    time: '25 min hands-on · 1 h rising',
    keeps: 'Room temperature 1 day · Freezer 2 months (cut into wedges)',
    reheat:
      'Frozen wedge: air fryer 180°C for 3–4 min, or a dry pan 2 minutes per side. No need to thaw.',
    ingredients: [
      [
        '250 g',
        'whole-wheat flour (farine complète), or barley flour for kesra chaïr',
        'flour-ww',
        250,
      ],
      ['250 g', 'fine semolina (smid fin)', 'semolina', 250],
      ['1 tsp', 'instant yeast'],
      ['1 tsp', 'salt'],
      ['2 tbsp', 'olive oil', 'olive-oil', 27],
      ['~300 ml', 'warm water (whole-wheat flour drinks more than white)'],
      ['1 tsp', 'nigella or sesame seeds (optional)'],
    ],
    steps: [
      'Mix the flour, semolina, yeast, salt and seeds. Add the oil and rub it in with your fingers.',
      'Add the warm water little by little and knead 8–10 minutes, until soft and slightly sticky.',
      'Divide into 3 balls. Flatten each into a disc about 1 cm thick and prick it all over with a fork.',
      'Cover with a clean cloth and leave to rise 45–60 minutes.',
      'Cook in a dry non-stick pan on medium-low for 6–8 minutes per side, turning a few times, until golden and it sounds hollow when tapped.',
      'Cool on a rack. Cut each round into 6 wedges and freeze them in a bag. One wedge is a portion.',
    ],
    alternative:
      "Barley flour (kesra chaïr) has more fibre and a nuttier taste. It's less stretchy, so knead gently and make the discs a little thicker.",
  },
  // Extras ------------------------------------------------------------------
  // Not in the 4-week rotation yet. Sized like the rotation dishes (see data.test.ts),
  // so any of them can replace a stew, second batch, tray bake or breakfast.

  goulash: {
    name: 'Beef goulash with sweet paprika',
    short: 'Goulash',
    local: 'Hungarian, made mild. Sweet paprika is the whole point',
    kind: 'stew',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker + pasta pot',
    time: '20 min hands-on · 35 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min with 1 tbsp water over the pasta, stir halfway.',
    cutter: [
      { head: 'slice-thick', what: '3 carrots' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['1 kg', 'lean beef chunks (épaule), 3 cm cubes', 'beef-chunks', 1000],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['2 cloves', 'garlic, grated (optional, fully cooked)'],
      ['3', 'carrots, thick slices on the cutter', 'carrot', 300],
      ['2', 'sweet peppers (not hot), in chunks', 'pepper', 300],
      ['2 tbsp', 'tomato paste', 'tomato-paste', 30],
      ['1 tbsp', 'sweet paprika (a full tablespoon, it makes the sauce)'],
      ['½ tsp', 'caraway seeds (karwiya), optional'],
      ['1 tsp', 'dried thyme or marjoram'],
      ['1', 'bay leaf'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['700 ml', 'water'],
      ['to serve', '300 g whole-wheat pasta (50 g per portion)', 'pasta-ww', 300],
    ],
    steps: [
      'Sauté mode: heat the oil and brown the beef in two batches, 4 minutes each. Add the onion and garlic for 3 minutes.',
      'Turn the heat off, then stir in the paprika and tomato paste. Paprika burns and turns bitter on high heat.',
      'Add the carrots, caraway, thyme, bay leaf, salt, pepper and water. Pressure 35 minutes, then let the pressure drop on its own for 10 minutes.',
      'Add the peppers. Sauté mode with the lid off for 8 minutes, until they soften and the sauce thickens.',
      'Boil the pasta 2 minutes less than the packet says. Pasta in each container, goulash on top.',
    ],
    alternative:
      'Slow cook: 7–8 hours on low, peppers for the last hour. On the stove: covered pot for 1½ hours, peppers for the last 20 minutes.',
  },
  'chicken-curry': {
    name: 'Mild chicken curry with chickpeas & spinach',
    short: 'Chicken curry',
    local: 'Indian korma-style, no chilli at all',
    kind: 'stew',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 8 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min with 1 tbsp water over the rice, stir halfway.',
    cutter: [{ head: 'grate-fine', what: '1 onion' }],
    ingredients: [
      ['1 kg', 'boneless skinless chicken thighs, in chunks', 'chicken-thigh', 1000],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['2 cloves', 'garlic, grated (optional, fully cooked)'],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['2 tsp', 'ground coriander'],
      ['1½ tsp', 'cumin'],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'ginger powder'],
      ['½ tsp', 'cinnamon'],
      ['4', 'cardamom pods, crushed (optional)'],
      ['1 tbsp', 'tomato paste', 'tomato-paste', 15],
      ['1½ tsp', 'salt'],
      ['400 g', 'cooked chickpeas (1 can, drained)', 'chickpeas', 400],
      ['300 g', 'frozen spinach (épinards surgelés)', 'spinach', 300],
      ['30 g', 'almonds, ground in the chopper. They thicken the sauce', 'nuts', 30],
      ['200 g', 'plain yogurt, stirred in at the end', 'yogurt', 200],
      ['300 ml', 'water'],
      ['to serve', '300 g rice (50 g per portion, see Rice)', 'rice', 300],
    ],
    steps: [
      'Sauté mode: oil, onion and garlic for 4 minutes. Add the chicken, spices, tomato paste and salt and stir for 5 minutes.',
      'Add the chickpeas, frozen spinach and water. Pressure 8 minutes, then quick release.',
      'Stir in the ground almonds. Sauté mode with the lid off for 5 minutes to thicken.',
      'Switch off and wait 5 minutes, then stir in the yogurt. Yogurt splits if it boils.',
      'Cook the rice. Rice in each container, curry on top.',
    ],
    alternative:
      'Slow cook: 4–5 hours on low, almonds and yogurt at the end. On the stove: covered pot for 30 minutes.',
  },
  'chicken-barley': {
    name: 'Chicken, barley & leek stew',
    short: 'Chicken & barley',
    local: 'British-style. Coarse dchicha works if there is no pearl barley',
    kind: 'stew',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 20 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat:
      'Add a splash of water (the barley keeps drinking the sauce), microwave 3 min, stir halfway.',
    cutter: [
      { head: 'slice-thick', what: '3 carrots, 1 zucchini, 1 leek' },
      { head: 'slice-thin', what: '200 g mushrooms' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['1.6 kg', 'chicken legs, skin removed, bone-in', 'chicken-leg', 1600],
      ['250 g', 'pearl barley (orge perlé) or coarse dchicha, rinsed', 'barley', 250],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['1', 'leek, thick slices on the cutter, washed well', 'leek', 200],
      ['3', 'carrots, thick slices on the cutter', 'carrot', 300],
      ['1', 'zucchini, thick slices on the cutter', 'zucchini', 250],
      ['200 g', 'mushrooms, thin slices on the cutter', 'mushrooms', 200],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['1 tsp', 'dried thyme'],
      ['1', 'bay leaf'],
      ['½ tsp', 'turmeric'],
      ['½ tsp', 'black pepper'],
      ['1', 'chicken stock cube'],
      ['1 tsp', 'salt (taste first, the cube is salty)'],
      ['1.3 L', 'water'],
      ['handful', 'parsley, chopped'],
    ],
    steps: [
      'Sauté mode: oil, chicken, onion, turmeric and pepper for 6 minutes.',
      'Add the barley, carrots, leek, mushrooms, thyme, bay leaf, stock cube and water. Pressure 20 minutes, then let the pressure drop on its own for 10 minutes.',
      'Lift out the chicken, pull the meat off the bones and put it back.',
      'Add the zucchini. Sauté mode with the lid off for 5 minutes. Taste for salt and add the parsley.',
    ],
    alternative:
      "Slow cook: 6 hours on low, zucchini for the last hour. On the stove: covered pot for 50 minutes, stirring now and then so the barley doesn't stick.",
  },
  'beef-bean-stew': {
    name: 'Beef, red bean & corn stew',
    short: 'Beef & red beans',
    local: 'Chili con carne without the chilli',
    kind: 'stew',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 35 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min, stir halfway. A spoon of yogurt on top once it is hot.',
    cutter: [
      { head: 'grate-coarse', what: '1 zucchini' },
      { head: 'grate-fine', what: '2 carrots, 1 onion' },
    ],
    ingredients: [
      ['800 g', 'lean beef mince (viande hachée)', 'beef-mince', 800],
      [
        '300 g',
        'dried red kidney beans (haricots rouges), soaked overnight and drained (or 3 cans, drained)',
        'kidney-beans',
        300,
      ],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['2 cloves', 'garlic, grated (optional)'],
      ['2', 'carrots, finely grated on the cutter', 'carrot', 200],
      ['1', 'zucchini, coarsely grated on the cutter', 'zucchini', 250],
      ['2', 'sweet peppers, small dice', 'pepper', 300],
      ['1 can', 'sweet corn, drained (about 285 g)', 'corn', 285],
      ['400 g', 'tomato passata', 'passata', 400],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['2 tsp', 'sweet paprika'],
      ['2 tsp', 'cumin'],
      ['1 tsp', 'dried oregano'],
      ['¼ tsp', 'cinnamon'],
      ['1 tsp', 'cocoa powder (optional, it deepens the sauce)'],
      ['¼ tsp', 'baking soda. Takes the acid edge off the tomato'],
      ['1½ tsp', 'salt'],
      ['600 ml', 'water (300 ml with canned beans)'],
    ],
    steps: [
      'Sauté mode: oil and mince, broken up, for 6 minutes. Add the onion, garlic, carrots and zucchini for 5 minutes.',
      'Turn the heat off. Stir in the spices, cocoa, passata and baking soda (it foams for a moment).',
      'Add the drained beans, salt and water. Pressure 35 minutes, then let the pressure drop on its own for 10 minutes. With canned beans, 8 minutes is enough.',
      'Add the peppers and corn. Sauté mode with the lid off for 8–10 minutes, until thick.',
    ],
    alternative:
      'Slow cook: boil the soaked beans hard in plain water for 10 minutes first (undercooked red kidney beans make you ill), then 7–8 hours on low. On the stove: covered pot for about 1½ hours.',
  },
  'split-pea-soup': {
    name: 'Split pea soup with chicken',
    short: 'Split pea soup',
    local: 'Soupe de pois cassés',
    kind: 'pot',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot + hand blender',
    time: '15 min hands-on · 45 min simmer',
    keeps: 'Fridge 4 days · Freezer 3 months',
    reheat: 'It sets thick in the fridge: add a good splash of water, microwave 3 min, stir.',
    cutter: [
      { head: 'slice-thin', what: '3 carrots, 1 potato, 1 leek' },
      { head: 'grate-coarse', what: '1 onion' },
    ],
    ingredients: [
      [
        '400 g',
        'dried green split peas (pois cassés), rinsed. No soaking needed',
        'split-peas',
        400,
      ],
      ['800 g', 'chicken breast, left whole', 'chicken-breast', 800],
      ['1', "onion, coarsely grated on the cutter (blended in, you won't taste it)", 'onion', 150],
      ['1', 'leek, thin slices on the cutter, washed well', 'leek', 200],
      ['3', 'carrots, thin slices on the cutter', 'carrot', 300],
      ['1', 'potato, thin slices on the cutter', 'potato', 200],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['1 tsp', 'cumin'],
      ['1 tsp', 'dried thyme'],
      ['1', 'bay leaf'],
      ['1', 'chicken stock cube'],
      ['1 tsp', 'salt (taste first, the cube is salty)'],
      ['2.3 L', 'water'],
    ],
    steps: [
      'Big pot: oil, onion and leek for 5 minutes, until soft.',
      'Add the split peas, carrots, potato, cumin, thyme, bay leaf, stock cube and water. Lay the chicken breasts in whole.',
      'Bring to a boil and skim off the foam. Simmer partly covered for 20 minutes, then lift out the chicken.',
      'Keep simmering 20–25 minutes more, stirring often (split peas stick), until the peas fall apart.',
      'Take out the bay leaf and blend smooth. Shred the chicken with two forks and stir it back in. Taste for salt.',
    ],
    alternative:
      'Multicooker: sauté the onion and leek, add everything else, pressure 15 minutes and let the pressure drop on its own. Then shred the chicken and blend.',
  },
  'shepherds-pie': {
    name: "Beef & lentil shepherd's pie",
    short: "Shepherd's pie",
    local: 'British cottage pie, with lentils and peas in the filling',
    kind: 'pot',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven dish + 2 pots',
    temp: '200°C (gas 6)',
    time: '40 min hands-on · 25 min oven',
    keeps: 'Fridge 4 days · Freezer 3 months',
    reheat: 'Covered, microwave 3 min, or oven 180°C for 15 min to crisp the top.',
    cutter: [
      { head: 'slice-thick', what: '1 kg potatoes (for the mash)' },
      { head: 'grate-fine', what: '3 carrots, 1 onion' },
    ],
    ingredients: [
      ['700 g', 'lean beef mince', 'beef-mince', 700],
      ['150 g', 'red lentils, rinsed', 'red-lentils', 150],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['3', 'carrots, finely grated on the cutter', 'carrot', 300],
      ['300 g', 'frozen peas', 'peas', 300],
      ['2 tbsp', 'tomato paste', 'tomato-paste', 30],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['1 tsp', 'dried thyme'],
      ['½ tsp', 'cinnamon (optional)'],
      ['1', 'beef or chicken stock cube'],
      ['500 ml', 'water'],
      ['1 kg', 'potatoes, thick slices on the cutter', 'potato', 1000],
      ['150 ml', 'milk for the mash', 'milk', 150],
      ['40 g', 'grated cheese for the top', 'grated-cheese', 40],
      ['1 tsp', 'salt · ½ tsp black pepper · pinch of nutmeg'],
    ],
    steps: [
      'Mash: boil the potato slices in salted water for 12–15 minutes until soft. Drain and mash with the warm milk, a pinch of salt and the nutmeg.',
      'Meanwhile, big pot: oil and mince for 6 minutes, breaking it up. Add the onion and carrots for 5 minutes.',
      "Stir in the tomato paste, thyme, cinnamon, lentils, crumbled stock cube and water. Simmer 15 minutes, until the lentils are soft and it's thick. Stir in the frozen peas.",
      'Oven to 200°C. Spread the filling in a large oven dish, cover with the mash, rough up the top with a fork and scatter the cheese.',
      'Bake 25 minutes until golden. Cool, then cut into 6.',
    ],
  },
  minestrone: {
    name: 'Chicken minestrone with white beans',
    short: 'Minestrone',
    local: 'Italian vegetable soup, made into a full meal',
    kind: 'pot',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot, stove',
    time: '20 min hands-on · 35 min simmer',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Add a splash of water (the pasta soaks up the broth), microwave 3 min.',
    cutter: [
      { head: 'slice-thin', what: '3 carrots, 1 leek' },
      { head: 'shred', what: '300 g cabbage' },
      { head: 'grate-coarse', what: '1 zucchini' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['700 g', 'chicken breast, left whole', 'chicken-breast', 700],
      ['200 g', 'dried white beans, soaked overnight (or 2 cans, drained)', 'white-beans', 200],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['1', 'leek, thin slices on the cutter, washed well', 'leek', 200],
      ['3', 'carrots, thin slices on the cutter', 'carrot', 300],
      ['300 g', 'white cabbage, shredded on the cutter', 'cabbage', 300],
      ['1', 'zucchini, coarsely grated on the cutter', 'zucchini', 250],
      ['250 g', 'tomato passata', 'passata', 250],
      ['120 g', 'small whole-wheat pasta (or broken spaghetti)', 'pasta-ww', 120],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['1 tsp', 'dried basil or oregano'],
      ['1', 'bay leaf'],
      ['1', 'chicken stock cube'],
      ['1 tsp', 'salt (taste first)'],
      ['2.5 L', 'water'],
      ['handful', 'parsley, chopped'],
    ],
    steps: [
      'Dried beans? Simmer the soaked beans in the 2.5 L of water for 40 minutes first, then carry on in the same water.',
      'Big pot: oil, onion and leek for 5 minutes, until soft.',
      'Add the water, beans, carrots, cabbage, passata, herbs, bay leaf, stock cube and the whole chicken breasts. Simmer covered for 20 minutes.',
      'Lift out the chicken and shred it. Add the pasta and zucchini and simmer 10 minutes more.',
      'Put the chicken back, add the parsley and taste for salt.',
    ],
  },
  moussaka: {
    name: 'Lighter moussaka',
    short: 'Moussaka',
    local: 'Greek, with roasted (not fried) eggplant and lentils in the meat sauce',
    kind: 'pot',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven dish + 2 trays + stove',
    temp: '200°C (gas 6)',
    time: '45 min hands-on · 35 min oven',
    keeps: 'Fridge 4 days · Freezer 3 months',
    reheat: 'Covered, microwave 3 min, or oven 180°C for 15 min.',
    cutter: [
      { head: 'slice-thick', what: '3 eggplants, 400 g potatoes' },
      { head: 'grate-fine', what: '1 onion' },
    ],
    ingredients: [
      ['3', 'eggplants (about 900 g), thick slices on the cutter', 'eggplant', 900],
      ['400 g', 'potatoes, thick slices on the cutter', 'potato', 400],
      ['2 tbsp', 'olive oil to brush the slices', 'olive-oil', 27],
      ['600 g', 'lean beef mince', 'beef-mince', 600],
      ['150 g', 'red lentils, rinsed', 'red-lentils', 150],
      ['1', 'onion, finely grated on the cutter', 'onion', 150],
      ['2 tbsp', 'tomato paste', 'tomato-paste', 30],
      ['200 g', 'tomato passata', 'passata', 200],
      ['1 tsp', 'cinnamon'],
      ['1 tsp', 'dried oregano'],
      ['1½ tsp', 'salt'],
      ['400 ml', 'water'],
      ['25 g', 'butter (béchamel)', 'butter', 25],
      ['35 g', 'flour (béchamel)', 'flour-white', 35],
      ['600 ml', 'semi-skimmed milk (béchamel)', 'milk', 600],
      ['1', 'egg, beaten into the béchamel', 'egg', 55],
      ['60 g', 'grated cheese', 'grated-cheese', 60],
      ['pinch', 'nutmeg · black pepper'],
    ],
    steps: [
      'Oven to 220°C. Brush the eggplant and potato slices with the oil, sprinkle with salt and spread over 2 trays. Roast 20 minutes until soft. Roasting instead of frying saves most of the oil.',
      'Meanwhile, big pot: mince and onion for 8 minutes. Add the tomato paste, passata, cinnamon, oregano, salt, lentils and water. Simmer 15 minutes until thick.',
      'Béchamel: melt the butter, whisk in the flour for 1 minute, then pour in the milk slowly, whisking. Simmer 5 minutes until thick. Off the heat, whisk in the egg, nutmeg and pepper.',
      'Oven down to 200°C. Layer a large dish: potatoes, half the eggplant, the meat sauce, the rest of the eggplant, then the béchamel and cheese.',
      'Bake 30–35 minutes until golden. Rest 20 minutes before cutting into 6, or it falls apart.',
    ],
  },
  'fish-tray': {
    name: 'Baked white fish with potatoes & zucchini',
    short: 'Fish tray',
    local: 'Frozen hake (colin) or fresh whiting (merlan)',
    kind: 'tray',
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '15 min hands-on · 40 min oven',
    keeps: "Fridge 3 days · Don't freeze",
    reheat:
      "Microwave 90 s covered. Fish dries out if you go longer, so it's also fine lukewarm with hot potatoes.",
    cutter: [{ head: 'slice-thick', what: '1 kg potatoes, 2 zucchini' }],
    ingredients: [
      [
        '800 g',
        'white fish fillets: hake (colin) or whiting (merlan), thawed if frozen',
        'white-fish',
        800,
      ],
      ['1 kg', 'potatoes, thick slices on the cutter', 'potato', 1000],
      ['2', 'zucchini, thick slices on the cutter', 'zucchini', 500],
      ['1', 'sweet pepper, in strips', 'pepper', 150],
      ['2 tbsp', 'olive oil', 'olive-oil', 27],
      ['2 tsp', 'sweet paprika'],
      ['1 tsp', 'cumin'],
      ['1 tsp', 'dried thyme'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['handful', 'parsley or dill, chopped'],
    ],
    steps: [
      'Oven to 210°C. Toss the potatoes, zucchini and pepper with 1½ tbsp oil, half the spices and 1 tsp salt on 2 trays. Roast 25 minutes.',
      'Pat the fish dry. Rub it with the rest of the oil, spices and salt.',
      'Lay the fish on top of the vegetables. Roast 12–15 minutes more, until it flakes with a fork.',
      "Parsley on top. Let it cool, then box the fish first so it doesn't break.",
    ],
  },
  'turkey-tray': {
    name: 'Zaatar turkey with cauliflower, eggplant & chickpeas',
    short: 'Zaatar turkey',
    local: 'Levantine-style tray bake',
    kind: 'tray',
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '220°C (gas 7–8)',
    time: '15 min hands-on · 35 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Microwave 2 min, or air fryer 180°C for 6 min. Yogurt-mint sauce cold on the side.',
    cutter: [{ head: 'slice-thick', what: '1 eggplant' }],
    ingredients: [
      ['800 g', 'turkey escalopes (escalopes de dinde), in strips', 'turkey-breast', 800],
      ['½', 'cauliflower (about 500 g), in small florets', 'cauliflower', 500],
      ['1', 'eggplant, thick slices on the cutter, then halved', 'eggplant', 300],
      ['400 g', 'cooked chickpeas (1 can), drained and patted dry', 'chickpeas', 400],
      ['2 tbsp', 'olive oil', 'olive-oil', 27],
      ['1 tbsp', 'zaatar or dried thyme'],
      ['1 tsp', 'cumin'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'turmeric'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
    ],
    steps: [
      'Oven to 220°C. Toss the cauliflower, eggplant and chickpeas with 1½ tbsp oil, the spices and 1 tsp salt on 2 trays. Roast 20 minutes.',
      'Toss the turkey with the rest of the oil and salt and a pinch of each spice.',
      "Push the vegetables aside and add the turkey in one layer. Roast 12–15 minutes more, until it's just cooked. Turkey breast dries out fast, so don't leave it longer.",
    ],
  },
  'fajita-tray': {
    name: 'Chicken fajita wraps, sheet-pan style',
    short: 'Fajita wraps',
    local: 'Mexican flavours, none of the heat',
    kind: 'tray',
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '220°C (gas 7–8)',
    time: '15 min hands-on · 25 min oven',
    keeps: 'Fridge 4 days (filling) · Wraps stay in their packet',
    reheat:
      'Filling: microwave 90 s. Wraps: 20 s in a dry pan. Fill, add the yogurt sauce and lettuce, roll.',
    cutter: [{ head: 'slice-thick', what: '1 zucchini' }],
    ingredients: [
      ['800 g', 'chicken breast, in strips', 'chicken-breast', 800],
      ['4', 'sweet peppers of different colours, in strips', 'pepper', 600],
      ['1', 'zucchini, thick slices on the cutter', 'zucchini', 250],
      ['1½ tbsp', 'olive oil', 'olive-oil', 20],
      ['2 tsp', 'sweet paprika'],
      ['2 tsp', 'cumin'],
      ['1 tsp', 'dried oregano'],
      ['½ tsp', 'ground coriander'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      [
        '8',
        'small wheat tortilla wraps (about 40 g each), 2 per meal. A kesra wedge works too',
        'tortilla',
        320,
      ],
    ],
    steps: [
      'Oven to 220°C. In a big bowl, mix the oil, spices and salt. Toss the chicken, peppers and zucchini in it.',
      'Chicken on one tray, vegetables on the other, so nothing is crowded.',
      'Roast 20–25 minutes, until the peppers have dark edges and the chicken is cooked through.',
      'Box the filling. Keep the wraps in their packet, or freeze them and take 2 out each morning.',
    ],
  },
  'stuffed-peppers': {
    name: 'Beef & rice stuffed peppers',
    short: 'Stuffed peppers',
    local: 'Dolma, made mild',
    kind: 'tray',
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Deep oven dish',
    temp: '190°C (gas 5)',
    time: '30 min hands-on · 55 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Microwave 2–3 min covered, with a spoon of the sauce over the top.',
    cutter: [
      { head: 'grate-coarse', what: '1 zucchini' },
      { head: 'grate-fine', what: '1 carrot, 1 onion' },
    ],
    ingredients: [
      ['8', 'sweet peppers, wide ones that stand up, tops cut off and seeds out', 'pepper', 1200],
      ['700 g', 'lean beef mince', 'beef-mince', 700],
      ['120 g', 'rice, rinsed. It cooks inside the peppers', 'rice', 120],
      ['1', 'onion, finely grated on the cutter (it bakes for an hour)', 'onion', 150],
      ['1', 'carrot, finely grated on the cutter', 'carrot', 100],
      ['1', 'zucchini, coarsely grated on the cutter and squeezed', 'zucchini', 250],
      ['handful', 'parsley and 1 tsp dried mint'],
      ['1 tsp', 'cinnamon'],
      ['1 tsp', 'sweet paprika'],
      ['1½ tsp', 'salt · ½ tsp black pepper'],
      ['200 g', 'tomato passata + 300 ml water, for the bottom of the dish', 'passata', 200],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
    ],
    steps: [
      'Oven to 190°C. Mix the mince, rice, onion, carrot, zucchini, herbs, spices and salt with your hands.',
      'Fill the peppers loosely (the rice swells) and stand them in a deep oven dish. Put the tops back on.',
      'Mix the passata with the water and oil and pour it around the peppers.',
      'Cover with foil and bake 40 minutes. Uncover and bake 10–15 minutes more, until the rice is soft.',
      'Two peppers per portion, with a spoon of the sauce.',
    ],
  },
  'baked-oats': {
    name: 'Banana & date baked oats',
    short: 'Baked oats',
    kind: 'breakfast',
    serves: 6,
    yieldUnit: 'squares',
    appliance: 'oven',
    where: 'Oven dish, about 20 × 30 cm',
    temp: '180°C (gas 4)',
    time: '10 min hands-on · 35 min oven',
    keeps: 'Fridge 5 days · Freezer 2 months',
    reheat: 'Cold, or microwave 40 s. A spoon of yogurt on top.',
    ingredients: [
      ['270 g', 'rolled oats', 'oats', 270],
      ['3', 'ripe bananas, mashed', 'banana', 360],
      ['4', 'eggs', 'egg', 220],
      ['500 ml', 'semi-skimmed milk', 'milk', 500],
      ['6', 'dates, chopped', 'dates', 48],
      ['30 g', 'almonds or walnuts, chopped', 'nuts', 30],
      ['2 tsp', 'cinnamon'],
      ['1 tsp', 'baking powder'],
      ['pinch', 'salt'],
      ['1 tsp', 'oil for the dish', 'olive-oil', 5],
    ],
    steps: [
      'Oven to 180°C. Oil the dish.',
      'Mash the bananas in a big bowl. Whisk in the eggs and milk.',
      'Stir in the oats, dates, nuts, cinnamon, baking powder and salt. Pour into the dish.',
      'Bake 30–35 minutes until set and golden. Cool and cut into 6 squares.',
      '3 go in the fridge (Mon–Wed), 3 in the freezer (Thu, Fri + spare).',
    ],
  },
  pancakes: {
    name: 'Oat & banana pancakes',
    short: 'Pancakes',
    kind: 'breakfast',
    serves: 5,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Blender + non-stick pan',
    time: '30 min',
    keeps: 'Fridge 3 days · Freezer 2 months',
    reheat: '3 pancakes: air fryer 170°C for 4 min (5 from frozen), or microwave 45 s.',
    ingredients: [
      ['250 g', 'rolled oats', 'oats', 250],
      ['2', 'ripe bananas', 'banana', 240],
      ['7', 'eggs', 'egg', 385],
      ['300 g', 'thick strained yogurt, or plain yogurt drained in a sieve', 'greek-yogurt', 300],
      ['150 ml', 'milk', 'milk', 150],
      ['2 tsp', 'baking powder'],
      ['1 tsp', 'cinnamon · pinch of salt'],
      ['1 tsp', 'oil for the pan', 'olive-oil', 5],
    ],
    steps: [
      'Blend everything except the oil until smooth. Rest 5 minutes so the oats thicken the batter.',
      'Non-stick pan on medium-low, wiped with a drop of oil. Small ladles of batter, about 2 minutes a side, until bubbles pop on top.',
      'Makes about 15. Cool on a rack, then 3 per box: 3 boxes in the fridge (Mon–Wed), 2 in the freezer (Thu, Fri).',
    ],
  },
  'chia-jars': {
    name: 'Yogurt, oat & chia jars',
    short: 'Chia jars',
    kind: 'breakfast',
    serves: 5,
    yieldUnit: 'jars',
    appliance: 'none',
    where: '5 jars',
    time: '10 min · no cooking',
    keeps: 'Fridge 5 days',
    reheat: 'Eat cold. Add the fruit in the morning.',
    ingredients: [
      ['150 g', 'rolled oats (30 g per jar)', 'oats', 150],
      ['50 g', 'chia seeds (10 g per jar)', 'chia', 50],
      ['500 g', 'thick strained yogurt (yaourt à la grecque)', 'greek-yogurt', 500],
      ['500 ml', 'semi-skimmed milk', 'milk', 500],
      ['5', 'dates, chopped', 'dates', 40],
      ['1 tsp', 'cinnamon'],
    ],
    steps: [
      'Divide the oats, chia, dates and cinnamon between the jars.',
      "Add 100 g yogurt and 100 ml milk to each. Close and shake hard so the chia doesn't clump.",
      'Shake again after 10 minutes, then into the fridge.',
      'Each morning: top with a chopped piece of fruit.',
    ],
  },
  'breakfast-wraps': {
    name: 'Egg & turkey breakfast wraps',
    short: 'Breakfast wraps',
    local: 'Freezer breakfast burritos, mild',
    kind: 'breakfast',
    serves: 8,
    yieldUnit: 'wraps',
    appliance: 'stove',
    where: 'Big non-stick pan',
    time: '25 min',
    keeps: 'Fridge 3 days · Freezer 2 months',
    reheat:
      'From frozen: take off the foil, microwave 90 s or air fryer 180°C for 8 min. Thawed: air fryer 180°C for 4 min.',
    cutter: [{ head: 'grate-coarse', what: '1 zucchini (squeeze it dry in a cloth)' }],
    ingredients: [
      ['8', 'wheat tortilla wraps (about 40 g each)', 'tortilla', 320],
      ['10', 'eggs', 'egg', 550],
      ['150 g', 'turkey breast slices (blanc de dinde), diced', 'turkey-slices', 150],
      ['60 g', 'grated cheese', 'grated-cheese', 60],
      ['1', 'zucchini, coarsely grated on the cutter and squeezed dry', 'zucchini', 250],
      ['1', 'sweet pepper, small dice', 'pepper', 150],
      ['½ tsp', 'salt · pinch of pepper · ½ tsp sweet paprika'],
      ['1 tsp', 'oil for the pan', 'olive-oil', 5],
    ],
    steps: [
      'Pan: oil, pepper and zucchini for 5 minutes, until the water has cooked off.',
      'Add the turkey, then the beaten eggs with the salt and paprika. Stir gently on low heat until just set. Cool 10 minutes.',
      'Warm the wraps for 10 s each so they fold without cracking. Fill each with an eighth of the egg and some cheese, fold in the sides and roll tight.',
      'Wrap each one in foil. 3 in the fridge, the rest in a freezer bag.',
    ],
  },
  hummus: {
    name: 'Hummus without garlic',
    short: 'Hummus',
    local: 'Smooth and mild: no garlic, no lemon',
    kind: 'snack',
    serves: 8,
    yieldUnit: 'portions',
    appliance: 'none',
    where: 'Hand blender or chopper',
    time: '10 min · no cooking',
    keeps: 'Fridge 5 days',
    reheat:
      '3 tbsp with cucumber and carrot sticks, or on a slice of bread. Take it out 10 minutes early, it tastes better not fridge-cold.',
    ingredients: [
      ['600 g', 'cooked chickpeas (2 cans, drained), keep the liquid', 'chickpeas', 600],
      ['60 g', 'tahini', 'peanut-butter', 60],
      ['2 tbsp', 'olive oil', 'olive-oil', 27],
      ['1 tsp', 'cumin'],
      ['1 tsp', 'salt'],
      ['4–6 tbsp', 'ice-cold water or liquid from the can'],
    ],
    steps: [
      'Blend the chickpeas, tahini, oil, cumin and salt.',
      'Add the cold water a spoon at a time and keep blending for 2–3 minutes, until very smooth and light.',
      'Into a box, with a drizzle of oil and a pinch of sweet paprika on top.',
    ],
  },
  'roasted-chickpeas': {
    name: 'Crunchy air-fried chickpeas',
    short: 'Crunchy chickpeas',
    kind: 'snack',
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker, air fryer mode',
    time: '5 min hands-on · 18 min air fryer',
    keeps: 'Closed jar at room temperature 3 days (they soften after that)',
    reheat: 'A handful instead of crisps. 2 minutes in the air fryer brings back the crunch.',
    ingredients: [
      ['400 g', 'cooked chickpeas (1 can), drained and dried well in a towel', 'chickpeas', 400],
      ['1 tbsp', 'olive oil', 'olive-oil', 14],
      ['1 tsp', 'sweet paprika · ½ tsp cumin · ½ tsp salt'],
    ],
    steps: [
      'Dry the chickpeas really well (wet ones steam). Toss with the oil.',
      'Air fryer 190°C for 15–18 minutes, shaking every 5, until they rattle.',
      'Toss with the spices and salt while hot. Cool completely before the jar, or they go soft.',
    ],
  },
  'tuna-dip': {
    name: 'Tuna & yogurt spread',
    short: 'Tuna spread',
    kind: 'snack',
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'none',
    where: 'Bowl + fork',
    time: '5 min',
    keeps: 'Fridge 3 days',
    reheat: 'Cold, with cucumber sticks or on a slice of bread. About 20 g of protein a portion.',
    cutter: [{ head: 'grate-coarse', what: '½ cucumber (squeeze it)' }],
    ingredients: [
      ['2 tins', 'tuna, natural or in oil, well drained (about 280 g)', 'tuna', 280],
      ['200 g', 'thick strained yogurt', 'greek-yogurt', 200],
      ['½', 'cucumber, coarsely grated on the cutter and squeezed', 'cucumber', 150],
      ['handful', 'parsley or dill, chopped'],
      ['pinch', 'salt · black pepper · cumin'],
    ],
    steps: [
      'Mash the tuna with a fork.',
      'Stir in the yogurt, cucumber, herbs, salt, pepper and cumin.',
      'Into a closed box in the fridge.',
    ],
  },
  bulgur: {
    name: 'Bulgur pilaf',
    short: 'Bulgur',
    local: 'Borghol. More fibre than rice, same job',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Pot with lid',
    time: '20 min, mostly waiting',
    keeps: 'Fridge 4 days · Freezer 2 months',
    reheat: '1 tbsp water on top, microwave covered 1–2 min.',
    ingredients: [
      ['300 g', 'coarse bulgur (50 g per portion)', 'bulgur', 300],
      ['1 tsp', 'olive oil', 'olive-oil', 5],
      ['600 ml', 'water or stock'],
      ['½ tsp', 'salt'],
    ],
    steps: [
      'Pot: oil and bulgur, stir for 1 minute.',
      'Add the water and salt and bring to a boil. Lid on, lowest heat, 12 minutes.',
      'Off the heat, put a clean towel under the lid and leave 10 minutes. Fluff with a fork.',
    ],
  },
});

export function getRecipe(id: RecipeId): Recipe {
  return RECIPES[id];
}

export function isRecipeId(value: string): value is RecipeId {
  return Object.hasOwn(RECIPES, value);
}
