import type { Ingredient, Recipe, RecipeId } from './types';

type RecipeInput = Omit<Recipe, 'id' | 'ingredients'> & {
  ingredients: readonly (readonly [qty: string, item: string])[];
};

function define(recipes: Record<RecipeId, RecipeInput>): Record<RecipeId, Recipe> {
  const out = {} as Record<RecipeId, Recipe>;
  for (const id of Object.keys(recipes) as RecipeId[]) {
    const { ingredients, ...rest } = recipes[id];
    out[id] = {
      id,
      ...rest,
      ingredients: ingredients.map(([qty, item]): Ingredient => ({ qty, item })),
    };
  }
  return out;
}

/*
 * House rules for every recipe (see CLAUDE.md): halal; sweet paprika only, nothing hot;
 * onion and garlic only grated into long-cooked sauces, never raw; no vinegar; tomato kept low.
 */
export const RECIPES = define({
  loubia: {
    name: 'Loubia with beef',
    short: 'Loubia',
    local: 'Loubia bel lham',
    kind: 'stew',
    week: 1,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 35 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat:
      'Microwave 3 min, stir halfway (stove: small pot, splash of water, 6 min). Toast a slice of frozen bread with it.',
    ingredients: [
      ['500 g', 'dried white beans, soaked overnight and drained (or 3 × 400 g cans, drained)'],
      ['600 g', 'beef chunks (épaule), 3 cm cubes'],
      ['1', "onion, grated. It melts into the sauce and you won't find any pieces"],
      ['2 cloves', 'garlic, grated (optional, fully cooked)'],
      ['2', 'carrots, sliced'],
      ['2 tbsp', 'tomato paste'],
      ['1 tsp', 'sweet paprika (paprika douce)'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'black pepper'],
      ['1', 'bay leaf'],
      ['1½ tsp', 'salt'],
      ['3 tbsp', 'olive oil'],
      ['1.2 L', 'water (1.8 L if using the stove)'],
      ['handful', 'parsley, chopped'],
    ],
    steps: [
      'Sauté mode: heat the oil and brown the beef with the onion and garlic for 8 minutes.',
      'Stir in the tomato paste, paprika, cumin and pepper. Cook 1 minute.',
      'Add the drained beans, carrots, bay leaf, salt and water. Close the lid.',
      'Pressure 35 minutes, then let the pressure drop on its own for 10 minutes.',
      "Taste for salt. If it's thin, simmer on sauté with the lid off for 5 minutes. Finish with parsley.",
    ],
    alternative:
      'Slow cook: boil the soaked beans hard in plain water for 10 minutes first (slow cookers never get hot enough to make dried beans safe), then 7–8 hours on low. Or a covered pot on the stove for about 1½ hours until the beans are soft.',
  },
  'chorba-frik': {
    name: 'Chorba frik with chicken',
    short: 'Chorba frik',
    local: 'Chorba frik (mild, no harissa)',
    kind: 'pot',
    week: 1,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot, stove',
    time: '20 min hands-on · 50 min simmer',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat:
      'Add a splash of water because it thickens. Microwave 3 min or small pot 5 min. Bread on the side.',
    ingredients: [
      ['4', 'chicken legs (~900 g)'],
      ['1', 'onion, grated'],
      ['2', 'carrots, small dice'],
      ['1', 'zucchini, small dice'],
      ['1', 'tomato, grated'],
      ['2 tbsp', 'tomato paste'],
      ['1 small can', 'chickpeas, drained (or 100 g dried, soaked)'],
      ['120 g', 'frik (crushed green wheat), rinsed'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1 tsp', 'dried mint'],
      ['2 tsp', 'salt'],
      ['2 tbsp', 'olive oil'],
      ['2.5 L', 'water'],
      ['1 bunch', 'coriander, chopped'],
    ],
    steps: [
      'Big pot, medium heat: oil, chicken, onion, paprika, cinnamon and pepper. Stir for 8 minutes.',
      'Add the tomato paste and grated tomato and cook 2 minutes.',
      'Add the water, carrots, chickpeas and salt. Cover and simmer 30 minutes.',
      'Lift out the chicken, shred the meat and throw away the skin and bones.',
      "Add the frik and zucchini. Simmer 20 minutes uncovered, stirring every few minutes so the frik doesn't stick.",
      'Put the chicken back and add the mint and coriander. It should be a thick soup, and it thickens more as it cools.',
    ],
  },
  'paprika-tray': {
    name: 'Paprika chicken, potatoes & carrots',
    short: 'Paprika chicken',
    kind: 'tray',
    week: 1,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '15 min hands-on · 50 min oven',
    keeps: "Fridge 4 days · Don't freeze (the potatoes go grainy)",
    reheat: 'Microwave 2 min, or air fryer 180°C for 6–8 min to make it crisp again.',
    ingredients: [
      ['4', 'chicken legs or thighs, bone-in (~1.1 kg)'],
      ['800 g', 'potatoes, cut in wedges'],
      ['3', 'carrots, cut in sticks'],
      ['1', 'zucchini, in chunks'],
      ['1', 'sweet pepper (not hot), in strips'],
      ['4 tbsp', 'olive oil'],
      ['2 tsp', 'sweet paprika'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'turmeric'],
      ['1 tsp', 'dried thyme'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
    ],
    steps: [
      'Oven to 210°C (gas 7). Line 2 trays with baking paper.',
      'In a big bowl, mix the oil, spices and salt. Toss the chicken and vegetables in it until everything is coated.',
      'Spread in one layer, using both trays so nothing is crowded (crowded vegetables steam instead of roasting). Chicken skin-side up.',
      "Roast 45–50 minutes and swap the trays halfway. It's done when the chicken juices run clear and the potatoes are golden.",
    ],
  },
  'tajine-chickpea': {
    name: 'Chicken & chickpea tajine',
    short: 'Chicken tajine',
    local: 'Tajine djej bel hummus',
    kind: 'stew',
    week: 2,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '15 min hands-on · 15 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min with the lid ajar. Sprinkle 1 tbsp water over the couscous first.',
    ingredients: [
      ['1.5 kg', 'chicken legs (6 pieces), or 1 kg boneless thighs'],
      ['1', 'onion, grated'],
      ['2 cloves', 'garlic, grated (optional)'],
      ['3 tbsp', 'olive oil'],
      ['1 tsp', 'ginger powder'],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1½ tsp', 'salt'],
      ['400 g', 'cooked chickpeas (1 can, or 150 g dried and soaked)'],
      ['4', 'carrots, in chunks'],
      ['2', 'zucchini, in chunks'],
      ['500 ml', 'water (800 ml if using the stove)'],
      ['handful', 'coriander and parsley'],
      ['to serve', '360 g couscous (see Couscous)'],
    ],
    steps: [
      'Sauté mode: oil, chicken, onion, garlic, spices and salt. Stir for 8 minutes.',
      'Add the chickpeas, carrots and water. Pressure 15 minutes, then quick release.',
      'Add the zucchini. Sauté mode with the lid off for 6–8 minutes, until the zucchini is tender and the sauce has reduced.',
      'Stir in the herbs. Put couscous in each container and add the tajine on top.',
    ],
    alternative:
      'Slow cook: 5–6 hours on low (zucchini for the last hour). On the stove: covered pot for 45 minutes, adding the zucchini for the last 15.',
  },
  'lentil-soup': {
    name: 'Red lentil & carrot soup',
    short: 'Lentil soup',
    local: 'Chorba adès',
    kind: 'pot',
    week: 2,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot + hand blender',
    time: '15 min hands-on · 25 min simmer',
    keeps: 'Fridge 4 days · Freezer 3 months',
    reheat:
      'Splash of water, microwave 3 min. Eat with bread and a spoon of yogurt. Add a boiled egg or cheese for protein.',
    ingredients: [
      ['400 g', 'red lentils, rinsed'],
      ['1', "onion, chopped (blended in, you won't taste it raw)"],
      ['3', 'carrots, chopped'],
      ['1', 'medium potato, chopped'],
      ['2 tbsp', 'olive oil'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'turmeric'],
      ['1 tsp', 'sweet paprika'],
      ['1', 'chicken stock cube'],
      ['2.2 L', 'water'],
      ['1 tsp', 'salt (taste first, the cube is salty)'],
    ],
    steps: [
      'Big pot: oil and onion for 5 minutes, until soft but not brown.',
      'Add the carrots, potato and spices and stir for 1 minute.',
      'Add the lentils, water and stock cube. Bring to a boil, then simmer partly covered for 25 minutes, stirring now and then.',
      'Blend smooth with the hand blender. Taste and add salt.',
    ],
  },
  'kefta-tray': {
    name: 'Baked kefta with potato wedges',
    short: 'Kefta tray',
    local: 'Kefta au four',
    kind: 'tray',
    week: 2,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '25 min hands-on · 45 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Microwave 2 min or air fryer 180°C for 6 min. Yogurt sauce cold on the side.',
    ingredients: [
      ['700 g', 'minced beef (viande hachée)'],
      ['1 small', 'onion, very finely grated and squeezed dry (optional, it cooks into the meat)'],
      ['handful', 'parsley, finely chopped'],
      ['1 tsp', 'cumin'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['1 tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['1', 'egg'],
      ['3 tbsp', 'breadcrumbs or oats'],
      ['800 g', 'potatoes, wedges'],
      ['2', 'sweet peppers, in strips'],
      ['1', 'zucchini, in chunks'],
      ['3 tbsp', 'olive oil + ½ tsp salt + ½ tsp paprika for the vegetables'],
      [
        'sauce',
        '2 pots plain yogurt, ½ cucumber grated and squeezed, pinch of salt, ½ tsp dried mint. No garlic',
      ],
    ],
    steps: [
      'Oven to 210°C. Toss the potatoes and vegetables with oil, salt and paprika on 2 trays. Roast 20 minutes.',
      'Meanwhile, mix all the kefta ingredients with your hands for 1 minute. With wet hands, shape about 18 small sausages.',
      'Add the kefta to the trays. Roast 20–25 minutes more and turn them once.',
      'Stir the yogurt sauce together. It keeps 3 days in the fridge.',
    ],
  },
  jelbana: {
    name: 'Peas with beef & carrots',
    short: 'Jelbana',
    local: 'Jelbana',
    kind: 'stew',
    week: 3,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '15 min hands-on · 30 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min, stir halfway. Bread or rice on the side.',
    ingredients: [
      ['600 g', 'beef chunks (or chicken legs)'],
      ['1', 'onion, grated'],
      ['3 tbsp', 'olive oil'],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'sweet paprika'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1½ tsp', 'salt'],
      ['3', 'carrots, in chunks'],
      ['800 g', 'frozen peas'],
      ['700 ml', 'water'],
      ['1 bunch', 'coriander, chopped'],
    ],
    steps: [
      'Sauté mode: oil, beef, onion, spices and salt. Stir for 8 minutes.',
      'Add the carrots and water. Pressure 25 minutes, then quick release.',
      'Add the frozen peas. Pressure 3 minutes (or simmer 10 minutes on sauté).',
      'Stir in the coriander.',
    ],
    alternative:
      'Slow cook: beef and carrots 7 hours on low, peas for the last 30 minutes. On the stove: 1 hour covered for the beef, then the peas for the last 15 minutes.',
  },
  'chorba-beida': {
    name: 'White chicken & chickpea soup',
    short: 'Chorba beida',
    local: 'Chorba beida',
    kind: 'pot',
    week: 3,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Big pot, stove',
    time: '15 min hands-on · 45 min simmer',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Add a good splash of water (the vermicelli soaks up liquid). Microwave 3 min.',
    ingredients: [
      ['4', 'chicken legs (~1 kg)'],
      ['1', 'onion, grated'],
      ['2 tbsp', 'butter or olive oil'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['1', 'chicken stock cube'],
      ['1 tsp', 'salt'],
      ['400 g', 'cooked chickpeas'],
      ['2.5 L', 'water'],
      ['100 g', "vermicelli (cheveux d'ange)"],
      ['1 bunch', 'parsley, chopped'],
    ],
    steps: [
      "Big pot: butter, chicken, onion, cinnamon and pepper for 6 minutes. Keep it pale, don't brown it.",
      'Add the water, chickpeas, stock cube and salt. Simmer covered for 35 minutes.',
      'Lift out the chicken, shred it and throw away the bones and skin.',
      'Add the vermicelli and cook 8 minutes. Put the chicken back and add the parsley.',
      'The traditional finish is egg yolk and lemon. Skip it, because lemon can bring on heartburn.',
    ],
  },
  'yogurt-tray': {
    name: 'Yogurt-marinated chicken with rice',
    short: 'Yogurt chicken',
    local: 'Mild, shawarma-style',
    kind: 'tray',
    week: 3,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '220°C (gas 7–8)',
    time: '15 min hands-on · 30 min marinate · 30 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Sprinkle 1 tbsp water over the rice, microwave 2 min. Yogurt-mint sauce on the side.',
    ingredients: [
      ['1 kg', 'boneless chicken thighs'],
      ['200 g', 'plain yogurt'],
      ['2 tbsp', 'olive oil'],
      ['2 tsp', 'sweet paprika'],
      ['1 tsp', 'cumin'],
      ['½ tsp', 'turmeric'],
      ['½ tsp', 'cinnamon'],
      ['1 tsp', 'salt'],
      ['½ tsp', 'black pepper'],
      ['3', 'sweet peppers, in strips'],
      ['2', 'zucchini, half-moons'],
      ['2 tbsp', 'olive oil + pinch of salt for the vegetables'],
      ['to serve', '300 g rice (see Rice) · yogurt with dried mint and salt'],
    ],
    steps: [
      'Mix the yogurt, oil, spices and salt. Coat the chicken and rest 30 minutes (or overnight on Saturday).',
      'Oven to 220°C. Vegetables with oil and salt on one tray, chicken spread out on the other.',
      'Roast 25–30 minutes, until the chicken has dark edges.',
      'Cook the rice while it roasts. Slice the chicken. Portion rice, chicken and vegetables into containers.',
    ],
  },
  zitoune: {
    name: 'Chicken with olives & mushrooms',
    short: 'Tajine zitoune',
    local: 'Tajine zitoune',
    kind: 'stew',
    week: 4,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'multicooker',
    where: 'Multicooker',
    time: '20 min hands-on · 15 min pressure',
    keeps: 'Fridge 3 days · Freezer 3 months',
    reheat: 'Microwave 3 min with 1 tbsp water over the rice.',
    ingredients: [
      ['1.5 kg', 'chicken legs'],
      ['1', 'onion, grated'],
      ['3 tbsp', 'olive oil'],
      ['1 tsp', 'turmeric'],
      ['1 tsp', 'ginger powder'],
      ['½ tsp', 'cinnamon'],
      ['½ tsp', 'black pepper'],
      ['½ tsp', 'salt (the olives are salty)'],
      ['3', 'carrots, sliced'],
      ['250 g', 'mushrooms, quartered (or 1 can)'],
      ['250 g', 'pitted green olives'],
      ['500 ml', 'water'],
      ['handful', 'parsley'],
      ['to serve', '360 g rice (see Rice)'],
    ],
    steps: [
      'Olives: boil 5 minutes in plain water and drain. This takes out the extra salt and bitterness.',
      'Sauté mode: oil, chicken, onion, spices and salt for 8 minutes.',
      'Add the carrots, mushrooms and water. Pressure 15 minutes, then quick release.',
      'Add the olives. Sauté mode with the lid off for 8 minutes to thicken. Taste before adding any salt. Parsley on top.',
    ],
    alternative:
      'Slow cook: 5–6 hours on low, olives for the last 30 minutes. On the stove: covered pot for 45 minutes, olives for the last 10.',
  },
  gratin: {
    name: 'Chicken & mushroom pasta bake',
    short: 'Pasta gratin',
    local: 'Gratin de pâtes',
    kind: 'pot',
    week: 4,
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven dish + stove',
    temp: '200°C (gas 6)',
    time: '30 min hands-on · 25 min oven',
    keeps: 'Fridge 4 days · Freezer 2 months',
    reheat: 'Covered, with a splash of milk: microwave 3 min, or oven 180°C for 15 min.',
    ingredients: [
      ['500 g', 'penne'],
      ['600 g', 'chicken breast, small cubes'],
      ['1 tbsp', 'olive oil + ½ tsp sweet paprika + pinch of salt'],
      ['1', 'zucchini, diced'],
      ['200 g', 'mushrooms, sliced'],
      ['60 g', 'butter'],
      ['60 g', 'flour'],
      ['900 ml', 'milk'],
      ['1 tsp', 'salt'],
      ['¼ tsp', 'black pepper · pinch of nutmeg'],
      ['200 g', 'grated cheese'],
    ],
    steps: [
      'Oven to 200°C. Boil the pasta 2 minutes less than the packet says and drain.',
      'Pan: oil, chicken, paprika and salt for 6 minutes. Add the zucchini and mushrooms for 5 more.',
      "Béchamel: melt the butter in a pot and whisk in the flour for 1 minute. Pour in the milk slowly, whisking all the time, and simmer 5 minutes until it's as thick as yogurt. Add salt, pepper and nutmeg.",
      'Mix the pasta, chicken and half the béchamel in a large oven dish. Pour the rest on top and add the cheese.',
      'Bake 25 minutes until golden. Cool, then cut into 6.',
    ],
  },
  'herb-tray': {
    name: 'Herb drumsticks, sweet potato & green beans',
    short: 'Herb drumsticks',
    kind: 'tray',
    week: 4,
    serves: 4,
    yieldUnit: 'portions',
    appliance: 'oven',
    where: 'Oven, 2 trays',
    temp: '210°C (gas 7)',
    time: '15 min hands-on · 45 min oven',
    keeps: 'Fridge 4 days',
    reheat: 'Microwave 2 min, or air fryer 180°C for 6–8 min.',
    ingredients: [
      ['8', 'chicken drumsticks (~1.2 kg)'],
      ['700 g', 'sweet potatoes (batata hlowa), cubed'],
      ['400 g', 'green beans, trimmed (fresh or frozen)'],
      ['4 tbsp', 'olive oil'],
      ['1 tsp', 'dried thyme (zaatar)'],
      ['1 tsp', 'sweet paprika'],
      ['1 tbsp', 'honey'],
      ['1½ tsp', 'salt'],
      ['½ tsp', 'black pepper'],
    ],
    steps: [
      'Oven to 210°C. Toss the drumsticks and sweet potato with oil, thyme, paprika, salt and pepper on 2 trays.',
      'Roast 25 minutes.',
      'Add the green beans (tossed in 1 tsp oil and a pinch of salt) and drizzle the honey over the sweet potatoes.',
      'Roast 20 minutes more. The drumsticks are done when the juices run clear.',
    ],
  },
  oats: {
    name: 'Overnight oats jars',
    short: 'Overnight oats',
    kind: 'breakfast',
    serves: 5,
    yieldUnit: 'jars',
    appliance: 'none',
    where: '5 jars',
    time: '10 min · no cooking',
    keeps: 'Fridge 5 days',
    reheat: 'Eat cold, or warm it for 1 min. Add half a banana in the morning.',
    ingredients: [
      ['250 g', 'rolled oats (50 g per jar)'],
      ['750 ml', 'milk, or half milk half lben'],
      ['5 tbsp', 'plain yogurt'],
      ['5 tsp', 'honey'],
      ['1 tsp', 'cinnamon'],
      ['10', 'dates, chopped'],
      ['handful', 'almonds or walnuts'],
    ],
    steps: [
      'Put 50 g oats in each jar.',
      'Divide the milk, yogurt, honey, cinnamon and dates between the jars.',
      'Close and shake. Into the fridge.',
      'Each morning: add half a banana or a few nuts.',
    ],
  },
  muffins: {
    name: 'Egg muffins',
    short: 'Egg muffins',
    kind: 'breakfast',
    serves: 12,
    yieldUnit: 'muffins',
    appliance: 'oven',
    where: '12-cup muffin tin',
    temp: '180°C (gas 4)',
    time: '10 min hands-on · 22 min oven',
    keeps: 'Fridge 3 days · Freezer 2 months',
    reheat:
      '2 muffins: microwave 45 s or air fryer 170°C for 4 min. Add bread and a piece of fruit.',
    ingredients: [
      ['10', 'eggs'],
      ['100 ml', 'milk'],
      ['100 g', 'grated cheese'],
      ['1', 'sweet pepper, small dice'],
      ['100 g', 'cachir nature (not the spicy kind), diced, or leftover chicken or mushrooms'],
      ['handful', 'parsley'],
      ['½ tsp', 'salt · pinch of pepper'],
      ['1 tbsp', 'oil for the tin'],
    ],
    steps: [
      'Oven to 180°C. Oil the tin well, including silicone ones.',
      'Whisk the eggs, milk, salt and pepper.',
      'Divide the pepper, cachir, cheese and parsley between the cups. Pour the egg over until each is ¾ full.',
      'Bake 20–22 minutes until the centres are set. Cool.',
      '6 go in the fridge (Mon–Wed), 6 go in the freezer (Thu, Fri + spare).',
    ],
  },
  'energy-balls': {
    name: 'Date & oat energy balls',
    short: 'Energy balls',
    kind: 'snack',
    serves: 16,
    yieldUnit: 'balls',
    appliance: 'none',
    where: 'Hand blender chopper',
    time: '15 min · no cooking',
    keeps: 'Fridge 2 weeks',
    reheat: "2 balls = one snack. Good with tea when you'd otherwise reach for biscuits.",
    ingredients: [
      ['200 g', 'soft dates (deglet nour), pitted'],
      ['100 g', 'rolled oats'],
      ['60 g', 'peanut butter or tahini'],
      ['50 g', 'almonds, walnuts or peanuts'],
      ['pinch', 'cinnamon'],
      ['1–2 tbsp', 'water if needed'],
    ],
    steps: [
      'Pulse the nuts and oats in the chopper.',
      "Add the dates, peanut butter and cinnamon. Blend until it clumps together, adding a little water if it's dry.",
      'Roll into about 16 balls. Keep in a closed box in the fridge.',
    ],
  },
  couscous: {
    name: 'Couscous, the fast way',
    short: 'Couscous',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'none',
    where: 'Bowl + kettle',
    time: '5 min',
    keeps: 'Fridge 4 days · Freezer (with the stew) 3 months',
    reheat: "Sprinkle with water before microwaving so it doesn't dry out.",
    ingredients: [
      ['360 g', 'medium couscous'],
      ['1 tbsp', 'olive oil'],
      ['½ tsp', 'salt'],
      ['420 ml', 'boiling water'],
      ['1 tbsp', 'butter'],
    ],
    steps: [
      'Rub the couscous with the oil and salt in a bowl.',
      'Pour over the boiling water, cover with a plate and wait 5 minutes.',
      'Fluff with a fork and stir in the butter. (Steaming it in a couscoussier tastes better, but this is the weekday version.)',
    ],
  },
  rice: {
    name: 'Rice on the stove',
    short: 'Rice',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Pot with lid',
    time: '25 min, mostly waiting',
    keeps: 'Fridge 3 days (cool it fast) · Freezer 2 months',
    reheat: '1 tbsp water on top, microwave covered until steaming.',
    ingredients: [
      ['300–360 g', 'rice (the week tells you how much)'],
      ['2 ×', 'its weight in water (600–720 ml)'],
      ['1 tbsp', 'oil'],
      ['½ tsp', 'salt'],
    ],
    steps: [
      'Rinse the rice until the water runs clearer.',
      'Bring the rice, water, oil and salt to a boil. Put the lid on and turn to the lowest heat for 15 minutes.',
      'Take off the heat and leave 10 minutes without lifting the lid.',
      'Cool it fast: spread it on a tray and get it into containers and the fridge within 1 hour.',
    ],
  },
  eggs: {
    name: 'Boiled eggs for the week',
    short: 'Boiled eggs',
    kind: 'basic',
    serves: 6,
    yieldUnit: 'portions',
    appliance: 'stove',
    where: 'Small pot',
    time: '12 min',
    keeps: 'Fridge 7 days, unpeeled',
    reheat: 'One egg and a piece of fruit makes a snack.',
    ingredients: [['6', 'eggs']],
    steps: [
      'Lower the eggs into boiling water with a spoon.',
      'Boil 10 minutes.',
      'Move them to cold water, then into the fridge with the shells on.',
    ],
  },
});

export function getRecipe(id: RecipeId): Recipe {
  return RECIPES[id];
}

export function isRecipeId(value: string): value is RecipeId {
  return Object.hasOwn(RECIPES, value);
}
